version: '3.7'

networks:
  exe:
    driver: bridge

services:
  git_server:
    user: "2999"
    restart: always
    container_name: git_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
#    entrypoint: ["rasa", "run", "--enable-api"]
#    env_file:
#      - ./.env.action_server
    volumes:
       - ./dist:/app/dist

    sysctls:
      - net.core.somaxconn=65535
    logging:
      driver: local
