version: '2.4'

networks:
  jshw1:
    driver: bridge

services:
  frontend:
    build: .
    image: frontend:latest
    container_name: frontend
    restart: always

    networks:
      - jshw1
#    environment:
    ports:
      - 3000:3000


