version: '2.4'

networks:
  jshw:
    driver: bridge

volumes:
  data:
  pgadmin-data:

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
#      - ./volumes/postgres-db:/var/lib/postgresql/backup
#      - ./volumes/postgres-db/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
#      - ./volumes/postgres-db/access.sh:/docker-entrypoint-initdb.d/access.sh
#      - ./volumes/postgres-db/restore.sh:/docker-entrypoint-initdb.d/restore.sh
    networks:
      - jshw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db
    networks:
      - jshw

  gitcraft:
    image: ssh-server-gitcraft:latest
    container_name: gitcraft
    restart: always
    volumes:
      - ./ssh-server/data:/app
      - ./ssh-server/server:/app/server
#      - ./ssh-server/data/authorized_keys/authorized_keys:/home/git/.ssh/authorized_keys
#      - ./ssh-server/keys/root_id_rsa:/root/.ssh/id_rsa
#      - ./ssh-server/keys/root_id_rsa.pub:/root/.ssh/id_rsa.pub
      - ./ssh-server/keys/root:/root/.ssh
      - ./ssh-server/keys/git:/home/git/.ssh
    depends_on:
      - postgres-db
    networks:
      - jshw
#    environment:
    ports:
      - 22:22
      - 8080:8080



